<?php

namespace Container2xzyIb4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q_Uyc74Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q.Uyc74' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q.Uyc74'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tricksRepository' => ['privates', 'App\\Repository\\TricksRepository', 'getTricksRepositoryService', true],
            'userEntity' => ['privates', '.errored..service_locator.q.Uyc74.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.q.Uyc74": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'tricksRepository' => 'App\\Repository\\TricksRepository',
            'userEntity' => 'App\\Entity\\User',
        ]);
    }
}
