<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerONj7YTp\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerONj7YTp/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerONj7YTp.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerONj7YTp\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerONj7YTp\App_KernelProdContainer([
    'container.build_hash' => 'ONj7YTp',
    'container.build_id' => 'e268b469',
    'container.build_time' => 1681591048,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerONj7YTp');
