<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTS1vxh6\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTS1vxh6/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTS1vxh6.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTS1vxh6\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTS1vxh6\App_KernelProdContainer([
    'container.build_hash' => 'TS1vxh6',
    'container.build_id' => '04f0a872',
    'container.build_time' => 1683310330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTS1vxh6');
