<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_commentary_index' => [[], ['_controller' => 'App\\Controller\\CommentaryController::index'], [], [['text', '/commentary/']], [], [], []],
    'app_commentary_new' => [[], ['_controller' => 'App\\Controller\\CommentaryController::new'], [], [['text', '/commentary/new']], [], [], []],
    'app_commentary_show' => [['id'], ['_controller' => 'App\\Controller\\CommentaryController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/commentary']], [], [], []],
    'app_commentary_delete' => [['id'], ['_controller' => 'App\\Controller\\CommentaryController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/commentary']], [], [], []],
    'accueil' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'app_medias_new' => [[], ['_controller' => 'App\\Controller\\MediasController::new'], [], [['text', '/medias/new']], [], [], []],
    'app_medias_show' => [['id'], ['_controller' => 'App\\Controller\\MediasController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/medias']], [], [], []],
    'app_medias_edit' => [['id'], ['_controller' => 'App\\Controller\\MediasController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/medias']], [], [], []],
    'app_medias_delete' => [['id'], ['_controller' => 'App\\Controller\\MediasController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/medias']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'app_trick_index' => [[], ['_controller' => 'App\\Controller\\TricksController::index'], [], [['text', '/tricks/']], [], [], []],
    'app_trick_show' => [['id'], ['_controller' => 'App\\Controller\\TricksController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tricks']], [], [], []],
    'app_trick_new' => [[], ['_controller' => 'App\\Controller\\TricksController::new'], [], [['text', '/tricks/new']], [], [], []],
    'app_trick_edit' => [['id'], ['_controller' => 'App\\Controller\\TricksController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/tricks']], [], [], []],
    'app_trick_delete' => [['id'], ['_controller' => 'App\\Controller\\TricksController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/tricks']], [], [], []],
    'api_genid' => [['id'], ['_controller' => 'api_platform.action.not_exposed', '_api_respond' => 'true'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/.well-known/genid']], [], [], []],
    'api_entrypoint' => [['index', '_format'], ['_controller' => 'api_platform.action.entrypoint', '_format' => '', '_api_respond' => 'true', 'index' => 'index'], ['index' => 'index'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', 'index', 'index', true], ['text', '/api']], [], [], []],
    'api_doc' => [['_format'], ['_controller' => 'api_platform.action.documentation', '_format' => '', '_api_respond' => 'true'], [], [['variable', '.', '[^/]++', '_format', true], ['text', '/api/docs']], [], [], []],
    'api_jsonld_context' => [['shortName', '_format'], ['_controller' => 'api_platform.jsonld.action.context', '_format' => 'jsonld', '_api_respond' => 'true'], ['shortName' => '[^.]+', '_format' => 'jsonld'], [['variable', '.', 'jsonld', '_format', true], ['variable', '/', '[^.]+', 'shortName', true], ['text', '/api/contexts']], [], [], []],
    'app_logout' => [[], [], [], [['text', '/logout']], [], [], []],
];
