<?php

namespace ContainerWTtRKU3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gmkk6NYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gmkk6NY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gmkk6NY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'trick' => ['privates', '.errored..service_locator.Gmkk6NY.App\\Entity\\Tricks', NULL, 'Cannot autowire service ".service_locator.Gmkk6NY": it references class "App\\Entity\\Tricks" but no such service exists.'],
            'tricksRepository' => ['privates', 'App\\Repository\\TricksRepository', 'getTricksRepositoryService', true],
        ], [
            'slugger' => '?',
            'trick' => 'App\\Entity\\Tricks',
            'tricksRepository' => 'App\\Repository\\TricksRepository',
        ]);
    }
}
