<?php

namespace ContainerWTtRKU3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HZX6eLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hZX6e_L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hZX6e_L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'tricksRepository' => ['privates', 'App\\Repository\\TricksRepository', 'getTricksRepositoryService', true],
        ], [
            'slugger' => '?',
            'tricksRepository' => 'App\\Repository\\TricksRepository',
        ]);
    }
}
