<?php

namespace ContainerJzcimAV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E7cCAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._E7cC_A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._E7cC_A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HomeController::home' => ['privates', '.service_locator.4ZU5zm2', 'get_ServiceLocator_4ZU5zm2Service', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.W1hlQDJ', 'get_ServiceLocator_W1hlQDJService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.mzjt3rI', 'get_ServiceLocator_Mzjt3rIService', true],
            'App\\Controller\\TricksController::delete' => ['privates', '.service_locator.B27dF8z', 'get_ServiceLocator_B27dF8zService', true],
            'App\\Controller\\TricksController::edit' => ['privates', '.service_locator.Gmkk6NY', 'get_ServiceLocator_Gmkk6NYService', true],
            'App\\Controller\\TricksController::index' => ['privates', '.service_locator.4ZU5zm2', 'get_ServiceLocator_4ZU5zm2Service', true],
            'App\\Controller\\TricksController::new' => ['privates', '.service_locator.hZX6e_L', 'get_ServiceLocator_HZX6eLService', true],
            'App\\Controller\\TricksController::show' => ['privates', '.service_locator.hAV0MEA', 'get_ServiceLocator_HAV0MEAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\HomeController:home' => ['privates', '.service_locator.4ZU5zm2', 'get_ServiceLocator_4ZU5zm2Service', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.W1hlQDJ', 'get_ServiceLocator_W1hlQDJService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.mzjt3rI', 'get_ServiceLocator_Mzjt3rIService', true],
            'App\\Controller\\TricksController:delete' => ['privates', '.service_locator.B27dF8z', 'get_ServiceLocator_B27dF8zService', true],
            'App\\Controller\\TricksController:edit' => ['privates', '.service_locator.Gmkk6NY', 'get_ServiceLocator_Gmkk6NYService', true],
            'App\\Controller\\TricksController:index' => ['privates', '.service_locator.4ZU5zm2', 'get_ServiceLocator_4ZU5zm2Service', true],
            'App\\Controller\\TricksController:new' => ['privates', '.service_locator.hZX6e_L', 'get_ServiceLocator_HZX6eLService', true],
            'App\\Controller\\TricksController:show' => ['privates', '.service_locator.hAV0MEA', 'get_ServiceLocator_HAV0MEAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\HomeController::home' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\TricksController::delete' => '?',
            'App\\Controller\\TricksController::edit' => '?',
            'App\\Controller\\TricksController::index' => '?',
            'App\\Controller\\TricksController::new' => '?',
            'App\\Controller\\TricksController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\HomeController:home' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\TricksController:delete' => '?',
            'App\\Controller\\TricksController:edit' => '?',
            'App\\Controller\\TricksController:index' => '?',
            'App\\Controller\\TricksController:new' => '?',
            'App\\Controller\\TricksController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
