<?php

namespace ContainerJzcimAV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTricks2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Gmkk6NY.App\Entity\Tricks' shared service.
     *
     * @return \App\Entity\Tricks
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Gmkk6NY": it references class "App\\Entity\\Tricks" but no such service exists.');
    }
}
