<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDf1beuC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDf1beuC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDf1beuC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDf1beuC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDf1beuC\App_KernelDevDebugContainer([
    'container.build_hash' => 'Df1beuC',
    'container.build_id' => '65cb42f9',
    'container.build_time' => 1683841458,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDf1beuC');
