<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYc6V5xb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYc6V5xb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYc6V5xb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYc6V5xb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYc6V5xb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yc6V5xb',
    'container.build_id' => '345777bd',
    'container.build_time' => 1684174764,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYc6V5xb');
