<?php

namespace ContainerONj7YTp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTricksRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TricksRepository' shared autowired service.
     *
     * @return \App\Repository\TricksRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TricksRepository'] = new \App\Repository\TricksRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
